service: Odin

provider:
  name: aws
  runtime: nodejs4.3
  stage: automation
  deploymentBucket: automation-serverlessartifact-${opt:accountId, env:ACCOUNT_ID}
  environment:
    ACCOUNT_ID: ${opt:accountId, env:ACCOUNT_ID}
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

functions:
  CheckStacks:
    handler: stacks/check.handler
    events:
      # 8 AM UTC / 3 AM ET, delete if older than 2 hours
      - schedule: cron(0 8 ? * * *)
        input:
          staleAfter: 2
      # Every 6 hours, delete if older than 12 hours
      - schedule: cron(0 */6 ? * * *)
        input:
          staleAfter: 12

  DeleteStacks:
    handler: stacks/delete.handler
    events:
      - sns: delete-stack

resources: