service: odin

provider:
  name: aws
  runtime: nodejs4.3
  stage: automation
  deploymentBucket: automation-serverlessartifact-${opt:accountId, env:ACCOUNT_ID}
  environment:
    ACCOUNT_ID: ${opt:accountId, env:ACCOUNT_ID}
    DELETE_STACK_TOPIC: arn:aws:sns:us-east-1:${opt:accountId, env:ACCOUNT_ID}:delete-stack
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action:
        - cloudFormation:DescribeStacks
        - cloudFormation:DeleteStack
    - Effect: Allow
      Resource: arn:aws:sns:us-east-1:${opt:accountId, env:ACCOUNT_ID}:delete-stack
      Action:
        - sns:Publish

functions:
  CheckStacks:
    handler: stacks/check.handler
    events:
      # 8 AM UTC / 3 AM ET, delete if older than 2 hours
      - schedule:
          rate: cron(0 8 ? * * *)
          input:
            staleAfter: 2
      # Every 1 hour, delete if older than 12 hours
      - schedule:
          rate: cron(0 */1 ? * * *)
          input:
            staleAfter: 12

  DeleteStacks:
    handler: stacks/delete.handler
    events:
      - sns: delete-stack

resources:
  Description: Automated service for destroying temporary stacks (retains production and automation stacks)