service: odin

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    DELETE_STACK_TOPIC:
      Fn::Join:
        - ':'
        - - arn:aws:sns:us-east-1
          - Ref: AWS::AccountId
          - delete-stack
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

functions:
  CheckStacks:
    handler: stacks/check.handler
    events:
      # 8 AM UTC / 3 AM ET, delete if older than 2 hours
      - schedule:
          rate: cron(0 8 ? * * *)
          input:
            staleAfter: 2
      # Every 1 hour, delete if older than 12 hours
      - schedule:
          rate: cron(0 */1 ? * * *)
          input:
            staleAfter: 12

  DeleteStacks:
    handler: stacks/delete.handler
    events:
      - sns: delete-stack

resources:
  Description: Automated service for destroying temporary stacks (retains production and automation stacks)
