service: Odin

provider:
  name: aws
  runtime: nodejs4.3
  stage: automation
  deploymentBucket: automation-serverlessartifact-${opt:accountId, env:ACCOUNT_ID}
  environment:
    ACCOUNT_ID: ${opt:accountId, env:ACCOUNT_ID}
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action:
        - sns:*
        - cloudformation:*

functions:
  CheckStacks:
    handler: stacks/check.handler
    events:
      # 4 AM UTC / 11 PM ET
      - schedule: cron(0 4 ? * * *)

  DeleteStacks:
    handler: stacks/delete.handler
    events:
      - sns: delete-stack
